-- ──────────────────────────────────────────────────────────────
-- Migration 007 — add brief cache columns to archives.
--
-- The director's pre-meeting brief is generated by Claude from family
-- contributions. To avoid burning AI tokens on every page load, we
-- cache the generated brief on the archive row. The LiveBriefPanel
-- shows the cached version immediately and only triggers a regenerate
-- when the brief is over an hour old AND new memories have arrived.
--
-- HOW TO RUN:
--   1. Open your Supabase project dashboard
--   2. SQL Editor → New query
--   3. Paste this file
--   4. Run
-- ──────────────────────────────────────────────────────────────

alter table archives
  add column if not exists brief_content text,
  add column if not exists brief_generated_at timestamptz,
  add column if not exists brief_memory_count integer default 0;

-- Index helps when checking staleness across multiple archives later
create index if not exists idx_archives_brief_generated_at
  on archives(brief_generated_at);
